# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 340)
        MainWindow.setStyleSheet("border: 3px solid #fff;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 16px;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(15, 5, 47, 13))
        self.image.setStyleSheet("border: 0px solid #fff;")
        self.image.setObjectName("image")
        self.temperature = QtWidgets.QLabel(self.centralwidget)
        self.temperature.setGeometry(QtCore.QRect(15, 175, 101, 41))
        self.temperature.setStyleSheet("font: 22pt \"Bahnschrift SemiLight\";\n"
"border: 1px solid #fff;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 16px;")
        self.temperature.setText("")
        self.temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature.setObjectName("temperature")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(325, 65, 181, 60))
        self.time.setStyleSheet("font: 57 48pt \"Yu Gothic\";")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(246, 135, 250, 50))
        self.date.setStyleSheet("font: 25 36pt \"Yu Gothic\";")
        self.date.setObjectName("date")
        self.weekday = QtWidgets.QLabel(self.centralwidget)
        self.weekday.setGeometry(QtCore.QRect(280, 245, 220, 80))
        self.weekday.setStyleSheet("font: 25 36pt \"Yu Gothic UI\";\n"
"border: 1px solid #fff;\n"
"border-color: rgb(0, 0, 0);")
        self.weekday.setAlignment(QtCore.Qt.AlignCenter)
        self.weekday.setObjectName("weekday")
        self.weather = QtWidgets.QLabel(self.centralwidget)
        self.weather.setGeometry(QtCore.QRect(15, 235, 201, 91))
        self.weather.setStyleSheet("border: 1px solid #fff;\n"
"font: 25 14pt \"Yu Gothic UI Light\";\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 16px;")
        self.weather.setText("")
        self.weather.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.weather.setObjectName("weather")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(460, 10, 30, 30))
        self.btn_close.setStyleSheet("border: 0px solid #fff;\n"
"font: 16pt \"Tahoma\";")
        self.btn_close.setObjectName("btn_close")
        self.wind = QtWidgets.QLabel(self.centralwidget)
        self.wind.setGeometry(QtCore.QRect(124, 175, 91, 41))
        self.wind.setAutoFillBackground(False)
        self.wind.setStyleSheet("font: 12pt \"Bahnschrift SemiLight\";\n"
"border: 1px solid #fff;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 16px;")
        self.wind.setText("")
        self.wind.setAlignment(QtCore.Qt.AlignCenter)
        self.wind.setWordWrap(False)
        self.wind.setObjectName("wind")
        self.city = QtWidgets.QLineEdit(self.centralwidget)
        self.city.setGeometry(QtCore.QRect(227, 10, 220, 34))
        self.city.setStyleSheet("font: 14pt \"Bahnschrift SemiLight\";\n"
"border: 1px solid #fff;\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 16px;")
        self.city.setAlignment(QtCore.Qt.AlignCenter)
        self.city.setObjectName("city")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.time.setText(_translate("MainWindow", "00:00"))
        self.date.setText(_translate("MainWindow", "01.01.2000"))
        self.weekday.setText(_translate("MainWindow", "Monday"))
        self.btn_close.setText(_translate("MainWindow", "х"))
        self.city.setText(_translate("MainWindow", "Severodvinsk,RU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
